export const language = {
  ENG: {
    date: 'DATE',
    assembly: 'Assembly',
    immageattached: 'IMAGE ATTACHED',
    notaskhistory: 'No task history',
    reload: 'Reload',
    datestamp: 'Date Stamp',
    hasmattress: 'Has mattress',
    new: 'New',
    submit: 'Submit',
    pleaseinputrequired: 'Please input required fields!',
    somethingwentwrong: 'Something went wrong!',
    trucknumber: 'Truck Number',
    back: 'Back',
    previousteam: 'Previous Team',
    scananother: 'Scan another',
    deliverdate: 'Deliver Date',
    servicetime: 'Service Time',
    volume: 'Volume',
    weight: 'Weight',
    servicename: 'Service Name',
    noordersfound: 'No orders found!',
    tryagain: 'Try Again',
    settings: 'Settings',
    account: 'Account',
    changepassword: 'Change Password',
    changelanguage: 'Change Language',
    isPDAMODE: 'PDA Mode',
    chooselanguage: 'Choose langugae',
    home: 'Home',
    receiving: 'Receiving',
    completeDelivery: 'Complete Delivery',
    return: 'Return',
    storagelocation: 'Storage Location',
    location: 'Location',
    loadtruck: 'Load Truck',
    ordersearch: 'Order Search',
    newtask: 'New Task',
    mytask: 'My Task',
    template: 'Template',
    customer: 'Customer',
    freightnoteno: 'FN #',
    productcondition: 'Product Condition',
    receivingdepartment: 'Receiving Department',
    jobstatus: 'Job Status',
    remarks: 'Remarks',
    attachimages: 'Attach Images',
    closetask: 'Close Task',
    housetype: 'House Type',
    logout: 'Logout',
    staging: 'Staging',
    stage: 'STAGE',
    presstoscan: 'Press to scan',
    good: 'Good',
    torn: 'Torn',
    scratched: 'Scratched',
    damaged: 'Damaged',
    discolored: 'Discolored',
    bill_no: 'Bill No.',
    scan_now: 'Scan now',
    deliveries: 'Deliveries',
    home_delivery: 'Home',
    driver: 'Driver',
    status_id: 'Status ID',
    row_code_no: 'Row Code No.',
    step_1: 'Step 1',
    step_2: 'Step 2',
    step_3: 'Step 3',
    hub_id: 'Hub Name',
    senders_name: 'Senders Name',
    drivers_license_plate: 'Drivers License Plate',
    branch_name: 'Branch Name',
    time_in: 'Date and Time',
    delivery_condition: 'Delivery Condition',
    delivery_status: 'Delivery Status',
    number_of_trays_sent: 'Number of Trays Sent',
    number_of_green_basket: 'Number of Green Basket',
    number_of_trays_store_received: 'Number of Trays Store Received',
    number_of_trays_hub_returned: 'Number of Trays Store Received',
    notes: 'Notes',
    picture_1: 'Picture 1',
    picture_2: 'Picture 2',
    signature: 'Signature',
    do_you_want_to_discard_your_changes:
      'Do you want to discard your changes?',
    choose: 'Choose',
    click_here: 'Click here',
    store: 'Store',
    done: 'Done',
    clear: 'Clear',
    store_name: 'Store Name',
    next: 'Next',
  },
  THAI: {
    date: 'วันที่',
    immageattached: 'แนบรูปภาพ',
    assembly: 'การประกอบ',
    notaskhistory: 'ไม่มีประวัติงาน',
    reload: 'โหลดซ้ำ',
    datestamp: 'แสตมป์วันที่',
    hasmattress: 'มีที่นอน',
    new: 'ใหม่',
    submit: 'ส่ง',
    pleaseinputrequired: 'กรุณากรอกข้อมูลในช่องที่ต้องกรอก!',
    somethingwentwrong: 'อะไรบางอย่างผิดปกติ!',
    trucknumber: 'หมายเลขรถบรรทุก',
    back: 'กลับ',
    previousteam: 'ทีมก่อนหน้า',
    scananother: 'สแกนอีกอัน',
    deliverdate: 'วันที่ส่งมอบ',
    servicetime: 'เวลาให้บริการ',
    volume: 'ปริมาณ',
    weight: 'น้ำหนัก',
    servicename: 'ชื่อบริการ',
    noordersfound: 'ไม่พบคำสั่งซื้อ',
    tryagain: 'ลองอีกครั้ง',
    settings: 'การตั้งค่า',
    account: 'บัญชีผู้ใช้',
    changepassword: 'เปลี่ยนรหัสผ่าน',
    changelanguage: 'เปลี่ยนภาษา',
    isPDAMODE: 'โหมดพีดีเอ',
    chooselanguage: 'เลือกภาษา',
    home: 'หน้าแรก',
    receiving: 'การได้มาซึ่ง',
    completeDelivery: 'เสร็จสิ้นการจัดส่ง',
    return: 'กลับ',
    storagelocation: 'สถานทจดเกบ',
    location: 'ที่ตั้ง',
    loadtruck: 'โหลดรถบรรทก',
    ordersearch: 'สงซอคนหา',
    newtask: 'งานใหม',
    mytask: 'งานของฉน',
    template: 'แมแบบ',
    customer: 'ลกคา',
    freightnoteno: 'เลขทใบกกบสนคา',
    productcondition: 'สภาพสนคา',
    receivingdepartment: 'ฝ่ายรับ',
    jobstatus: 'สถานะงาน',
    remarks: 'หมายเหต',
    attachimages: 'แนบรปภาพ',
    closetask: 'ปดงาน',
    housetype: 'แบบบาน',
    logout: 'ออกจากระบบ',
    staging: 'จัดฉาก',
    stage: 'เวที',
    presstoscan: 'กดเพื่อสแกน',
    good: 'ดี',
    torn: 'ฉีกขาด',
    scratched: 'มีรอยขีดข่วน',
    damaged: 'แตกหักแล้ว',
    discolored: 'ดำๆ ด่างๆ',
    bill_no: 'หมายเลขเอกสาร',
    scan_now: 'ตรวจเดี๋ยวนี้',
    deliveries: 'การส่งมอบ',
    home_delivery: 'บ้าน',
    driver: 'คนขับรถ',
    status_id: 'รหัสสถานะ',
    row_code_no: 'รหัสแถว',
    step_1: 'ขั้นตอนที่ 1',
    step_2: 'ขั้นตอนที่ 2',
    step_3: 'ขั้นตอนที่ 3',
    hub_id: 'ชื่อฮับ',
    senders_name: 'ชื่อผู้ส่ง',
    drivers_license_plate: 'ป้ายทะเบียนรถ',
    branch_name: 'ชื่อสาขา',
    time_in: 'วันและเวลา',
    delivery_condition: 'สภาพการจัดส่ง',
    delivery_status: 'สถานะการจัดส่ง',
    number_of_trays_sent: 'จำนวนถาดที่ส่ง',
    number_of_green_basket: 'จำนวนตะกร้าสีเขียว',
    number_of_trays_store_received: 'จำนวนถาดที่จัดเก็บที่ได้รับ',
    number_of_trays_hub_returned: 'จำนวนถาดฮับที่ส่งคืน',
    notes: 'หมายเหตุ',
    picture_1: 'ภาพที่ 1',
    picture_2: 'ภาพที่ 2',
    signature: 'ลายเซ็น',
    do_you_want_to_discard_your_changes:
      'คุณต้องการยกเลิกการเปลี่ยนแปลงของคุณหรือไม่?',
    choose: 'เลือก',
    click_here: 'คลิกที่นี่',
    store: 'เก็บ',
    done: 'เสร็จแล้ว',
    clear: 'ชัดเจน',
    store_name: 'ชื่อร้าน',
    next: 'ต่อไป',
  },
};
