const fetchLanguage = [
  {
    date: 'DATE',
    assembly: 'Assembly',
    immageattached: 'IMAGE ATTACHED',
    notaskhistory: 'No task history',
    reload: 'Reload',
    datestamp: 'Date Stamp',
    hasmattress: 'Has mattress',
    new: 'New',
    submit: 'Submit',
    pleaseinputrequired: 'Please input required fields!',
    somethingwentwrong: 'Something went wrong!',
    trucknumber: 'Truck Number',
    back: 'Back',
    previousteam: 'Previous Team',
    scananother: 'Scan another',
    deliverdate: 'Deliver Date',
    servicetime: 'Service Time',
    volume: 'Volume',
    weight: 'Weight',
    servicename: 'Service Name',
    noordersfound: 'No orders found!',
    tryagain: 'Try Again',
    settings: 'Settings',
    account: 'Account',
    changepassword: 'Change Password',
    changelanguage: 'Change Language',
    isPDAMODE: 'PDA Mode',
    chooselanguage: 'Choose langugae',
    settings: 'Settings',
    home: 'Home',
    receiving: 'Receiving',
    completeDelivery: 'Complete Delivery',
    return: 'Return',
    storagelocation: 'Storage Location',
    location: 'Location',
    loadtruck: 'Load Truck',
    ordersearch: 'Order Search',
    settings: 'Settings',
    newtask: 'New Task',
    mytask: 'My Task',
    template: 'Template',
    customer: 'Customer',
    freightnoteno: 'FN #',
    productcondition: 'Product Condition',
    receivingdepartment: 'Receiving Department',
    jobstatus: 'Job Status',
    remarks: 'Remarks',
    attachimages: 'Attach Images',
    closetask: 'Close Task',
    housetype: 'House Type',
    logout: 'Logout',
    staging: 'Staging',
    stage: 'STAGE',
    presstoscan: 'Press to scan',
    good: 'Good',
    torn: 'Torn',
    scratched: 'Scratched',
    damaged: 'Damaged',
    discolored: 'Discolored',
    bill_no: 'Bill No.',
    scan_now: 'Scan now',
    deliveries: 'Deliveries',
    home_delivery: 'Home',
  },
  {
    date: 'วันที่',
    immageattached: 'แนบรูปภาพ',
    assembly: 'การประกอบ',
    notaskhistory: 'ไม่มีประวัติงาน',
    reload: 'โหลดซ้ำ',
    datestamp: 'แสตมป์วันที่',
    hasmattress: 'มีที่นอน',
    new: 'ใหม่',
    submit: 'ส่ง',
    pleaseinputrequired: 'กรุณากรอกข้อมูลในช่องที่ต้องกรอก!',
    somethingwentwrong: 'อะไรบางอย่างผิดปกติ!',
    trucknumber: 'หมายเลขรถบรรทุก',
    back: 'กลับ',
    previousteam: 'ทีมก่อนหน้า',
    scananother: 'สแกนอีกอัน',
    deliverdate: 'วันที่ส่งมอบ',
    servicetime: 'เวลาให้บริการ',
    volume: 'ปริมาณ',
    weight: 'น้ำหนัก',
    servicename: 'ชื่อบริการ',
    noordersfound: 'ไม่พบคำสั่งซื้อ',
    tryagain: 'ลองอีกครั้ง',
    settings: 'การตั้งค่า',
    account: 'บัญชีผู้ใช้',
    changepassword: 'เปลี่ยนรหัสผ่าน',
    changelanguage: 'เปลี่ยนภาษา',
    isPDAMODE: 'โหมดพีดีเอ',
    chooselanguage: 'เลือกภาษา',
    home: 'บาน',
    receiving: 'การได้มาซึ่ง',
    completeDelivery: 'เสร็จสิ้นการจัดส่ง',
    return: 'กลับ',
    storagelocation: 'สถานทจดเกบ',
    location: 'ที่ตั้ง',
    loadtruck: 'โหลดรถบรรทก',
    ordersearch: 'สงซอคนหา',
    settings: 'การตงคา',
    newtask: 'งานใหม',
    mytask: 'งานของฉน',
    template: 'แมแบบ',
    customer: 'ลกคา',
    freightnoteno: 'เลขทใบกกบสนคา',
    productcondition: 'สภาพสนคา',
    receivingdepartment: 'ฝ่ายรับ',
    jobstatus: 'สถานะงาน',
    remarks: 'หมายเหต',
    attachimages: 'แนบรปภาพ',
    closetask: 'ปดงาน',
    housetype: 'แบบบาน',
    logout: 'ออกจากระบบ',
    staging: 'จัดฉาก',
    stage: 'เวที',
    presstoscan: 'กดเพื่อสแกน',
    good: 'ดี',
    torn: 'ฉีกขาด',
    scratched: 'มีรอยขีดข่วน',
    damaged: 'แตกหักแล้ว',
    discolored: 'ดำๆ ด่างๆ',
    bill_no: 'หมายเลขเอกสาร',
    scan_now: 'ตรวจเดี๋ยวนี้',
    deliveries: 'Deliveries',
    home_delivery: 'Home Delivery',
  },
];

export default fetchLanguage;
